SET search_path TO public;

DELETE FROM public.permissions;
INSERT INTO public.permissions (name, level, resource, action, description)
	VALUES
		('self.user.read', 'self', 'user', 'read', 'View own user profile'),
		('self.user.update', 'self', 'user', 'update', 'Update own user profile'),
		('self.org.create', 'self', 'org', 'create', 'Create own organization'),
		('self.feedback.create', 'self', 'feedback', 'create', 'Create own feedback issue'),
		('self.feedback.read', 'self', 'feedback', 'read', 'View own feedback issues'),
		('self.feedback.list', 'self', 'feedback', 'list', 'List own feedback issues'),
		('self.feedback.update', 'self', 'feedback', 'update', 'Update own feedback issues'),
		('system.user.read', 'system', 'user', 'read', 'View any user in system'),
		('system.user.list', 'system', 'user', 'list', 'List all users in system'),
		('system.user.create', 'system', 'user', 'create', 'Create users across system'),
		('system.user.update', 'system', 'user', 'update', 'Update any user in system'),
		('system.user.manage', 'system', 'user', 'manage', 'Full system-wide user management'),
		('system.permission.read', 'system', 'permission', 'read', 'View permissions within system'),
		('system.permission.list', 'system', 'permission', 'list', 'List all permissions in system'),
		('system.org.read', 'system', 'org', 'read', 'View any organization in system'),
		('system.org.list', 'system', 'org', 'list', 'List all organizations in system'),
		('system.role.read', 'system', 'role', 'read', 'View any role in system'),
		('system.role.list', 'system', 'role', 'list', 'List all roles in system'),
		('system.role.create', 'system', 'role', 'create', 'Create system roles'),
		('system.role.update', 'system', 'role', 'update', 'Update any role in system'),
		('system.report.manage', 'system', 'report', 'manage', 'Full system-wide report management'),
		('system.report.read', 'system', 'report', 'read', 'View any report in system'),
		('system.report.list', 'system', 'report', 'list', 'List all reports in system'),
		('system.report.create', 'system', 'report', 'create', 'Create reports across system'),
		('system.report.update', 'system', 'report', 'update', 'Update any report in system'),
		('system.report.delete', 'system', 'report', 'delete', 'Delete any report from system'),
		('system.billing.manage', 'system', 'billing', 'manage', 'Full billing management'),
		('system.billing.read', 'system', 'billing', 'read', 'View billing'),
		('system.billing.create', 'system', 'billing', 'create', 'Create billing'),
		('system.billing.update', 'system', 'billing', 'update', 'Update billing'),
		('system.billing.delete', 'system', 'billing', 'delete', 'Delete billing'),
		('system.payment.manage', 'system', 'payment', 'manage', 'Full payment management'),
		('system.payment.read', 'system', 'payment', 'read', 'View payments'),
		('system.payment.create', 'system', 'payment', 'create', 'Create payments'),
		('system.payment.update', 'system', 'payment', 'update', 'Update payments'),
		('system.payment.delete', 'system', 'payment', 'delete', 'Delete payments'),
		('system.invoice.manage', 'system', 'invoice', 'manage', 'Full invoice management'),
		('system.invoice.read', 'system', 'invoice', 'read', 'View invoices'),
		('system.invoice.create', 'system', 'invoice', 'create', 'Create invoices'),
		('system.invoice.update', 'system', 'invoice', 'update', 'Update invoices'),
		('system.invoice.delete', 'system', 'invoice', 'delete', 'Delete invoices'),
		('system.feedback.create', 'system', 'feedback', 'create', 'Create feedback issues across system'),
		('system.feedback.read', 'system', 'feedback', 'read', 'View any feedback issue in system'),
		('system.feedback.list', 'system', 'feedback', 'list', 'List all feedback issues in system'),
		('system.feedback.update', 'system', 'feedback', 'update', 'Update any feedback issue in system'),
		('org.org.read', 'org', 'org', 'read', 'View own organization'),
		('org.org.update', 'org', 'org', 'update', 'Update own organization'),
		('org.invitation.manage', 'org', 'invitation', 'manage', 'Full invitation management within organization'),
		('org.invitation.create', 'org', 'invitation', 'create', 'Create invitation from organization'),
		('org.invitation.list', 'org', 'invitation', 'list', 'List invitations within organization'),
		('org.invitation.read', 'org', 'invitation', 'read', 'View invitations within organization'),
		('org.invitation.update', 'org', 'invitation', 'update', 'Update invitations within organization'),
		('org.invitation.delete', 'org', 'invitation', 'delete', 'Delete invitations from organization'),
		('org.material.manage', 'org', 'material', 'manage', 'Full material management within organization'),
		('org.material.create', 'org', 'material', 'create', 'Create material from organization'),
		('org.material.read', 'org', 'material', 'read', 'View material within organization'),
		('org.material.list', 'org', 'material', 'list', 'List material within organization'),
		('org.material.update', 'org', 'material', 'update', 'Update material within organization'),
		('org.material.delete', 'org', 'material', 'delete', 'Delete material from organization'),
		('org.team.manage', 'org', 'team', 'manage', 'Full team management within organization'),
		('org.team.create', 'org', 'team', 'create', 'Create team from organization'),
		('org.team.read', 'org', 'team', 'read', 'View teams within organization'),
		('org.team.list', 'org', 'team', 'list', 'List teams within organization'),
		('org.team.update', 'org', 'team', 'update', 'Update teams within organization'),
		('org.team.delete', 'org', 'team', 'delete', 'Delete teams from organization'),
		('org.team_member.manage', 'org', 'team_member', 'manage', 'Full team member management within organization'),
		('org.team_member.create', 'org', 'team_member', 'create', 'Create team member from organization'),
		('org.team_member.read', 'org', 'team_member', 'read', 'View team members within organization'),
		('org.team_member.list', 'org', 'team_member', 'list', 'List team members within organization'),
		('org.team_member.update', 'org', 'team_member', 'update', 'Update team members within organization'),
		('org.team_member.delete', 'org', 'team_member', 'delete', 'Delete team members from organization'),
		('org.user.manage', 'org', 'user', 'manage', 'Full user management within organization'),
		('org.user.read', 'org', 'user', 'read', 'View users within organization'),
		('org.user.list', 'org', 'user', 'list', 'List all users in organization'),
		('org.user.create', 'org', 'user', 'create', 'Create new users in organization'),
		('org.user.update', 'org', 'user', 'update', 'Update users within organization'),
		('org.user.delete', 'org', 'user', 'delete', 'Delete users from organization'),
		('org.role.read', 'org', 'role', 'read', 'View roles within organization'),
		('org.role.list', 'org', 'role', 'list', 'List all roles in organization'),
		('org.role.create', 'org', 'role', 'create', 'Create custom roles in organization'),
		('org.role.update', 'org', 'role', 'update', 'Update roles within organization'),
		('org.role.delete', 'org', 'role', 'delete', 'Delete roles from organization'),
		('org.role.manage', 'org', 'role', 'manage', 'Full role management within organization'),
		('org.permission.read', 'org', 'permission', 'read', 'View permissions within organization'),
		('org.permission.list', 'org', 'permission', 'list', 'List all permissions in organization'),
		('org.permission.manage', 'org', 'permission', 'manage', 'Full permission management within organization'),
		('org.permission.update', 'org', 'permission', 'update', 'Update roles within organization'),
		('org.permission.delete', 'org', 'permission', 'delete', 'Delete roles within organization'),
		('org.schedule.manage', 'org', 'schedule', 'manage', 'Full schedule management within organization'),
		('org.schedule.create', 'org', 'schedule', 'create', 'Create schedule from organization'),
		('org.schedule.read', 'org', 'schedule', 'read', 'View schedules within organization'),
		('org.schedule.list', 'org', 'schedule', 'list', 'List all schedules in organization'),
		('org.schedule.update', 'org', 'schedule', 'update', 'Update schedules within organization'),
		('org.schedule.delete', 'org', 'schedule', 'delete', 'Delete schedules from organization'),
		('org.customer.manage', 'org', 'customer', 'manage', 'Full customer management within organization'),
		('org.customer.create', 'org', 'customer', 'create', 'Create customer from organization'),
		('org.customer.read', 'org', 'customer', 'read', 'View customers within organization'),
		('org.customer.list', 'org', 'customer', 'list', 'List customers within organization'),
		('org.customer.update', 'org', 'customer', 'update', 'Update customers within organization'),
		('org.customer.delete', 'org', 'customer', 'delete', 'Delete customers from organization'),
		('org.invoice.manage', 'org', 'invoice', 'manage', 'Full invoice management within organization'),
		('org.invoice.create', 'org', 'invoice', 'create', 'Create invoice from organization'),
		('org.invoice.read', 'org', 'invoice', 'read', 'View invoices within organization'),
		('org.invoice.list', 'org', 'invoice', 'list', 'List invoices within organization'),
		('org.invoice.update', 'org', 'invoice', 'update', 'Update invoices within organization'),
		('org.invoice.delete', 'org', 'invoice', 'delete', 'Delete invoices from organization'),
		('org.payment.manage', 'org', 'payment', 'manage', 'Full payment management within organization'),
		('org.payment.create', 'org', 'payment', 'create', 'Create payment from organization'),
		('org.payment.read', 'org', 'payment', 'read', 'View payments within organization'),
		('org.payment.list', 'org', 'payment', 'list', 'List payments within organization'),
		('org.payment.update', 'org', 'payment', 'update', 'Update payments within organization'),
		('org.payment.delete', 'org', 'payment', 'delete', 'Delete payments from organization'),
		('org.billing.manage', 'org', 'billing', 'manage', 'Full billing management within organization'),
		('org.billing.create', 'org', 'billing', 'create', 'Create billing from organization'),
		('org.billing.read', 'org', 'billing', 'read', 'View billings within organization'),
		('org.billing.list', 'org', 'billing', 'list', 'List all billings in organization'),
		('org.billing.update', 'org', 'billing', 'update', 'Update billings within organization'),
		('org.billing.delete', 'org', 'billing', 'delete', 'Delete billings from organization'),
		('org.report.manage', 'org', 'report', 'manage', 'Full report management within organization'),
		('org.report.create', 'org', 'report', 'create', 'Create report from organization'),
		('org.report.read', 'org', 'report', 'read', 'View reports within organization'),
		('org.report.list', 'org', 'report', 'list', 'List all reports in organization'),
		('org.report.update', 'org', 'report', 'update', 'Update reports within organization'),
		('org.report.delete', 'org', 'report', 'delete', 'Delete reports from organization'),
		('org.lead.manage', 'org', 'lead', 'manage', 'Full leads management within organization'),
		('org.lead.create', 'org', 'lead', 'create', 'Create lead from organization'),
		('org.lead.read', 'org', 'lead', 'read', 'View leads within organization'),
		('org.lead.list', 'org', 'lead', 'list', 'List all leads in organization'),
		('org.lead.update', 'org', 'lead', 'update', 'Update leads within organization'),
		('org.lead.delete', 'org', 'lead', 'delete', 'Delete leads from organization'),
		('org.lead_attachment.manage', 'org', 'lead_attachment', 'manage', 'Full lead attachment management within organization'),
		('org.lead_attachment.create', 'org', 'lead_attachment', 'create', 'Create lead attachment from organization'),
		('org.lead_attachment.read', 'org', 'lead_attachment', 'read', 'View lead attachments within organization'),
		('org.lead_attachment.list', 'org', 'lead_attachment', 'list', 'List all lead attachments in organization'),
		('org.lead_attachment.update', 'org', 'lead_attachment', 'update', 'Update lead attachments within organization'),
		('org.lead_attachment.delete', 'org', 'lead_attachment', 'delete', 'Delete lead attachments from organization'),
		('org.lead_note.manage', 'org', 'lead_note', 'manage', 'Full lead note management within organization'),
		('org.lead_note.create', 'org', 'lead_note', 'create', 'Create lead note from organization'),
		('org.lead_note.read', 'org', 'lead_note', 'read', 'View lead notes within organization'),
		('org.lead_note.list', 'org', 'lead_note', 'list', 'List all lead notes in organization'),
		('org.lead_note.update', 'org', 'lead_note', 'update', 'Update lead notes within organization'),
		('org.lead_note.delete', 'org', 'lead_note', 'delete', 'Delete lead notes from organization'),
		('org.lead_category.manage', 'org', 'lead_category', 'manage', 'Full lead category management within organization'),
		('org.lead_category.create', 'org', 'lead_category', 'create', 'Create lead category from organization'),
		('org.lead_category.read', 'org', 'lead_category', 'read', 'View lead categories within organization'),
		('org.lead_category.list', 'org', 'lead_category', 'list', 'List all lead categories in organization'),
		('org.lead_category.update', 'org', 'lead_category', 'update', 'Update lead categories within organization'),
		('org.lead_category.delete', 'org', 'lead_category', 'delete', 'Delete lead categories from organization'),
		('org.lead_invoice.manage', 'org', 'lead_invoice', 'manage', 'Full lead invoice management within organization'),
		('org.lead_invoice.create', 'org', 'lead_invoice', 'create', 'Create lead invoice from organization'),
		('org.lead_invoice.read', 'org', 'lead_invoice', 'read', 'View lead invoices within organization'),
		('org.lead_invoice.list', 'org', 'lead_invoice', 'list', 'List all lead invoices in organization'),
		('org.lead_invoice.update', 'org', 'lead_invoice', 'update', 'Update lead invoices within organization'),
		('org.lead_invoice.delete', 'org', 'lead_invoice', 'delete', 'Delete lead invoices from organization'),
		('org.lead_payment.manage', 'org', 'lead_payment', 'manage', 'Full lead payment management within organization'),
		('org.lead_payment.create', 'org', 'lead_payment', 'create', 'Create lead payment from organization'),
		('org.lead_payment.read', 'org', 'lead_payment', 'read', 'View lead payments within organization'),
		('org.lead_payment.list', 'org', 'lead_payment', 'list', 'List all lead payments in organization'),
		('org.lead_payment.update', 'org', 'lead_payment', 'update', 'Update lead payments within organization'),
		('org.lead_payment.delete', 'org', 'lead_payment', 'delete', 'Delete lead payments from organization'),
		('org.lead_billing.manage', 'org', 'lead_billing', 'manage', 'Full lead billing management within organization'),
		('org.lead_billing.create', 'org', 'lead_billing', 'create', 'Create lead billing from organization'),
		('org.lead_billing.read', 'org', 'lead_billing', 'read', 'View lead billings within organization'),
		('org.lead_billing.list', 'org', 'lead_billing', 'list', 'List all lead billings in organization'),
		('org.lead_billing.update', 'org', 'lead_billing', 'update', 'Update lead billings within organization'),
		('org.lead_billing.delete', 'org', 'lead_billing', 'delete', 'Delete lead billings from organization'),
		('org.lead_report.manage', 'org', 'lead_report', 'manage', 'Full lead report management within organization'),
		('org.lead_report.create', 'org', 'lead_report', 'create', 'Create lead report from organization'),
		('org.lead_report.read', 'org', 'lead_report', 'read', 'View lead reports within organization'),
		('org.lead_report.list', 'org', 'lead_report', 'list', 'List all lead reports in organization'),
		('org.lead_report.update', 'org', 'lead_report', 'update', 'Update lead reports within organization'),
		('org.lead_report.delete', 'org', 'lead_report', 'delete', 'Delete lead reports from organization'),
		('org.lead_estimate.manage', 'org', 'lead_estimate', 'manage', 'Full lead estimate management within organization'),
		('org.lead_estimate.create', 'org', 'lead_estimate', 'create', 'Create lead estimate from organization'),
		('org.lead_estimate.read', 'org', 'lead_estimate', 'read', 'View lead estimates within organization'),
		('org.lead_estimate.list', 'org', 'lead_estimate', 'list', 'List all lead estimates in organization'),
		('org.lead_estimate.update', 'org', 'lead_estimate', 'update', 'Update lead estimates within organization'),
		('org.lead_estimate.delete', 'org', 'lead_estimate', 'delete', 'Delete lead estimates from organization'),
		('org.job.manage', 'org', 'job', 'manage', 'Full job management within organization'),
		('org.job.create', 'org', 'job', 'create', 'Create job from organization'),
		('org.job.read', 'org', 'job', 'read', 'View jobs within organization'),
		('org.job.list', 'org', 'job', 'list', 'List all jobs in organization'),
		('org.job.update', 'org', 'job', 'update', 'Update jobs within organization'),
		('org.job.delete', 'org', 'job', 'delete', 'Delete jobs from organization'),
		('org.job_category.manage', 'org', 'job_category', 'manage', 'Full job category management within organization'),
		('org.job_category.create', 'org', 'job_category', 'create', 'Create job category from organization'),
		('org.job_category.read', 'org', 'job_category', 'read', 'View job categories within organization'),
		('org.job_category.list', 'org', 'job_category', 'list', 'List all job categories in organization'),
		('org.job_category.update', 'org', 'job_category', 'update', 'Update job categories within organization'),
		('org.job_category.delete', 'org', 'job_category', 'delete', 'Delete job categories from organization'),
		('org.job_material.manage', 'org', 'job_material', 'manage', 'Full job material management within organization'),
		('org.job_material.create', 'org', 'job_material', 'create', 'Create job material from organization'),
		('org.job_material.read', 'org', 'job_material', 'read', 'View job materials within organization'),
		('org.job_material.list', 'org', 'job_material', 'list', 'List all job materials in organization'),
		('org.job_material.update', 'org', 'job_material', 'update', 'Update job materials within organization'),
		('org.job_material.delete', 'org', 'job_material', 'delete', 'Delete job materials from organization'),
		('org.job_revenue.manage', 'org', 'job_revenue', 'manage', 'Full job revenue management within organization'),
		('org.job_revenue.read', 'org', 'job_revenue', 'read', 'View job revenues within organization'),
		('org.job_revenue.list', 'org', 'job_revenue', 'list', 'List all job revenues in organization'),
		('org.job_revenue.update', 'org', 'job_revenue', 'update', 'Update job revenues within organization'),
		('org.job_assignment.manage', 'org', 'job_assignment', 'manage', 'Full job assignment management within organization'),
		('org.job_assignment.create', 'org', 'job_assignment', 'create', 'Create job assignment from organization'),
		('org.job_assignment.read', 'org', 'job_assignment', 'read', 'View job assignments within organization'),
		('org.job_assignment.list', 'org', 'job_assignment', 'list', 'List all job assignments in organization'),
		('org.job_assignment.update', 'org', 'job_assignment', 'update', 'Update job assignments within organization'),
		('org.job_assignment.delete', 'org', 'job_assignment', 'delete', 'Delete job assignments from organization'),
		('org.job_attachment.manage', 'org', 'job_attachment', 'manage', 'Full job attachment management within organization'),
		('org.job_attachment.create', 'org', 'job_attachment', 'create', 'Create job attachment from organization'),
		('org.job_attachment.read', 'org', 'job_attachment', 'read', 'View job attachments within organization'),
		('org.job_attachment.list', 'org', 'job_attachment', 'list', 'List all job attachments in organization'),
		('org.job_attachment.update', 'org', 'job_attachment', 'update', 'Update job attachments within organization'),
		('org.job_attachment.delete', 'org', 'job_attachment', 'delete', 'Delete job attachments from organization'),
		('org.job_note.manage', 'org', 'job_note', 'manage', 'Full job note management within organization'),
		('org.job_note.create', 'org', 'job_note', 'create', 'Create job note from organization'),
		('org.job_note.read', 'org', 'job_note', 'read', 'View job notes within organization'),
		('org.job_note.list', 'org', 'job_note', 'list', 'List all job notes in organization'),
		('org.job_note.update', 'org', 'job_note', 'update', 'Update job notes within organization'),
		('org.job_note.delete', 'org', 'job_note', 'delete', 'Delete job notes from organization'),
		('org.job_invoice.manage', 'org', 'job_invoice', 'manage', 'Full job invoice management within organization'),
		('org.job_invoice.create', 'org', 'job_invoice', 'create', 'Create job invoice from organization'),
		('org.job_invoice.read', 'org', 'job_invoice', 'read', 'View job invoices within organization'),
		('org.job_invoice.list', 'org', 'job_invoice', 'list', 'List all job invoices in organization'),
		('org.job_invoice.update', 'org', 'job_invoice', 'update', 'Update job invoices within organization'),
		('org.job_invoice.delete', 'org', 'job_invoice', 'delete', 'Delete job invoices from organization'),
		('org.job_payment.manage', 'org', 'job_payment', 'manage', 'Full job payment management within organization'),
		('org.job_payment.create', 'org', 'job_payment', 'create', 'Create job payment from organization'),
		('org.job_payment.read', 'org', 'job_payment', 'read', 'View job payments within organization'),
		('org.job_payment.list', 'org', 'job_payment', 'list', 'List all job payments in organization'),
		('org.job_payment.update', 'org', 'job_payment', 'update', 'Update job payments within organization'),
		('org.job_payment.delete', 'org', 'job_payment', 'delete', 'Delete job payments from organization'),
		('org.job_billing.manage', 'org', 'job_billing', 'manage', 'Full job billing management within organization'),
		('org.job_billing.create', 'org', 'job_billing', 'create', 'Create job billing from organization'),
		('org.job_billing.read', 'org', 'job_billing', 'read', 'View job billings within organization'),
		('org.job_billing.list', 'org', 'job_billing', 'list', 'List all job billings in organization'),
		('org.job_billing.update', 'org', 'job_billing', 'update', 'Update job billings within organization'),
		('org.job_billing.delete', 'org', 'job_billing', 'delete', 'Delete job billings from organization'),
		('org.job_estimate.manage', 'org', 'job_estimate', 'manage', 'Full job estimate management within organization'),
		('org.job_estimate.create', 'org', 'job_estimate', 'create', 'Create job estimate from organization'),
		('org.job_estimate.read', 'org', 'job_estimate', 'read', 'View job estimates within organization'),
		('org.job_estimate.list', 'org', 'job_estimate', 'list', 'List all job estimates in organization'),
		('org.job_estimate.update', 'org', 'job_estimate', 'update', 'Update job estimates within organization'),
		('org.job_estimate.delete', 'org', 'job_estimate', 'delete', 'Delete job estimates from organization'),
		('org.job_time_entry.manage', 'org', 'job_time_entry', 'manage', 'Full job time entry management within organization'),
		('org.job_time_entry.create', 'org', 'job_time_entry', 'create', 'Create job time entry from organization'),
		('org.job_time_entry.read', 'org', 'job_time_entry', 'read', 'View job time entries within organization'),
		('org.job_time_entry.list', 'org', 'job_time_entry', 'list', 'List all job time entries in organization'),
		('org.job_time_entry.update', 'org', 'job_time_entry', 'update', 'Update job time entries within organization'),
		('org.job_time_entry.delete', 'org', 'job_time_entry', 'delete', 'Delete job time entries from organization');

DELETE FROM public.roles;
INSERT INTO public.roles (role_name, type, description)
	VALUES
		('USER', 'SYSTEM', 'Regular user with basic self-management permissions'),
		('SYSTEM_SUPPORT_AGENT', 'SYSTEM', 'System support agent'),
		('SYSTEM_ADMIN', 'SYSTEM', 'System administrator with organization-level access'),
		('SUPER_ADMIN', 'SYSTEM', 'Full system access'),
		('MEMBER', 'ORG', 'Basic organization member'),
		('STAFF', 'ORG', 'Organization staff member'),
		('DISPATCHER', 'ORG', 'Organization dispatcher'),
		('TEAM_LEAD', 'ORG', 'Organization team lead'),
		('MANAGER', 'ORG', 'Organization manager'),
		('ORG_SUPPORT_AGENT', 'ORG', 'Organization support agent'),
		('ORG_ADMIN', 'ORG', 'Organization administrator'),
		('OWNER', 'ORG', 'Organization owner with full org access');

DELETE FROM public.role_permissions;
WITH role_perm_mapping (role_name, role_type, permission_name) AS (
	VALUES
		('USER', 'SYSTEM', 'self.user.read'),
		('USER', 'SYSTEM', 'self.user.update'),
		('USER', 'SYSTEM', 'self.org.create'),
		('USER', 'SYSTEM', 'self.org.list'),
		('USER', 'SYSTEM', 'self.invitation.list'),
		('USER', 'SYSTEM', 'self.invitation.update'),
		('USER', 'SYSTEM', 'self.feedback.create'),
		('USER', 'SYSTEM', 'self.feedback.read'),
		('USER', 'SYSTEM', 'self.feedback.list'),
		('USER', 'SYSTEM', 'self.feedback.update'),
		('SYSTEM_SUPPORT_AGENT', 'SYSTEM', 'self.user.read'),
		('SYSTEM_SUPPORT_AGENT', 'SYSTEM', 'self.user.update'),
		('SYSTEM_SUPPORT_AGENT', 'SYSTEM', 'system.org.list'),
		('SYSTEM_SUPPORT_AGENT', 'SYSTEM', 'system.org.read'),
		('SYSTEM_SUPPORT_AGENT', 'SYSTEM', 'system.user.read'),
		('SYSTEM_SUPPORT_AGENT', 'SYSTEM', 'system.user.list'),
		('SYSTEM_SUPPORT_AGENT', 'SYSTEM', 'system.feedback.create'),
		('SYSTEM_SUPPORT_AGENT', 'SYSTEM', 'system.feedback.read'),
		('SYSTEM_SUPPORT_AGENT', 'SYSTEM', 'system.feedback.list'),
		('SYSTEM_SUPPORT_AGENT', 'SYSTEM', 'system.feedback.update'),
		('SYSTEM_ADMIN', 'SYSTEM', 'self.user.read'),
		('SYSTEM_ADMIN', 'SYSTEM', 'self.user.update'),
		('SYSTEM_ADMIN', 'SYSTEM', 'system.org.list'),
		('SYSTEM_ADMIN', 'SYSTEM', 'system.org.read'),
		('SYSTEM_ADMIN', 'SYSTEM', 'system.org.update'),
		('SYSTEM_ADMIN', 'SYSTEM', 'system.user.read'),
		('SYSTEM_ADMIN', 'SYSTEM', 'system.user.list'),
		('SYSTEM_ADMIN', 'SYSTEM', 'system.user.update'),
		('SYSTEM_ADMIN', 'SYSTEM', 'system.user.delete'),
		('SYSTEM_ADMIN', 'SYSTEM', 'system.role.read'),
		('SYSTEM_ADMIN', 'SYSTEM', 'system.role.list'),
		('SYSTEM_ADMIN', 'SYSTEM', 'system.role.update'),
		('SYSTEM_ADMIN', 'SYSTEM', 'system.permission.read'),
		('SYSTEM_ADMIN', 'SYSTEM', 'system.permission.list'),
		('SYSTEM_ADMIN', 'SYSTEM', 'system.invoice.manage'),
		('SYSTEM_ADMIN', 'SYSTEM', 'system.payment.manage'),
		('SYSTEM_ADMIN', 'SYSTEM', 'system.billing.manage'),
		('SYSTEM_ADMIN', 'SYSTEM', 'system.report.manage'),
		('SYSTEM_ADMIN', 'SYSTEM', 'system.report.export'),
		('SYSTEM_ADMIN', 'SYSTEM', 'system.feedback.create'),
		('SYSTEM_ADMIN', 'SYSTEM', 'system.feedback.read'),
		('SYSTEM_ADMIN', 'SYSTEM', 'system.feedback.list'),
		('SYSTEM_ADMIN', 'SYSTEM', 'system.feedback.update'),
		('SUPER_ADMIN', 'SYSTEM', 'self.user.read'),
		('SUPER_ADMIN', 'SYSTEM', 'self.user.update'),
		('SUPER_ADMIN', 'SYSTEM', 'system.user.manage'),
		('SUPER_ADMIN', 'SYSTEM', 'system.org.manage'),
		('SUPER_ADMIN', 'SYSTEM', 'system.role.read'),
		('SUPER_ADMIN', 'SYSTEM', 'system.role.list'),
		('SUPER_ADMIN', 'SYSTEM', 'system.role.update'),
		('SUPER_ADMIN', 'SYSTEM', 'system.permission.read'),
		('SUPER_ADMIN', 'SYSTEM', 'system.permission.list'),
		('SUPER_ADMIN', 'SYSTEM', 'system.invoice.manage'),
		('SUPER_ADMIN', 'SYSTEM', 'system.payment.manage'),
		('SUPER_ADMIN', 'SYSTEM', 'system.billing.manage'),
		('SUPER_ADMIN', 'SYSTEM', 'system.report.manage'),
		('SUPER_ADMIN', 'SYSTEM', 'system.feedback.create'),
		('SUPER_ADMIN', 'SYSTEM', 'system.feedback.read'),
		('SUPER_ADMIN', 'SYSTEM', 'system.feedback.list'),
		('SUPER_ADMIN', 'SYSTEM', 'system.feedback.update'),
		('MEMBER', 'ORG', 'org.user.read'),
		('MEMBER', 'ORG', 'org.user.list'),
		('MEMBER', 'ORG', 'org.team.list'),
		('MEMBER', 'ORG', 'org.team.read'),
		('STAFF', 'ORG', 'org.user.read'),
		('STAFF', 'ORG', 'org.user.list'),
		('STAFF', 'ORG', 'org.team.list'),
		('STAFF', 'ORG', 'org.team.read'),
		('STAFF', 'ORG', 'org.customer.list'),
		('STAFF', 'ORG', 'org.customer.read'),
		('STAFF', 'ORG', 'org.job.list'),
		('STAFF', 'ORG', 'org.job.read'),
		('STAFF', 'ORG', 'org.job.update'),
		('STAFF', 'ORG', 'org.job_attachment.create'),
		('STAFF', 'ORG', 'org.job_attachment.read'),
		('STAFF', 'ORG', 'org.job_note.create'),
		('STAFF', 'ORG', 'org.job_note.read'),
		('STAFF', 'ORG', 'org.job_time_entry.create'),
		('STAFF', 'ORG', 'org.job_time_entry.read'),
		('STAFF', 'ORG', 'org.job_time_entry.update'),
		('STAFF', 'ORG', 'org.lead.list'),
		('STAFF', 'ORG', 'org.lead.read'),
		('STAFF', 'ORG', 'org.lead_note.create'),
		('STAFF', 'ORG', 'org.lead_note.read'),
		('STAFF', 'ORG', 'org.schedule.list'),
		('STAFF', 'ORG', 'org.schedule.read'),
		('STAFF', 'ORG', 'org.material.list'),
		('STAFF', 'ORG', 'org.material.read'),
		('DISPATCHER', 'ORG', 'org.user.read'),
		('DISPATCHER', 'ORG', 'org.user.list'),
		('DISPATCHER', 'ORG', 'org.team.list'),
		('DISPATCHER', 'ORG', 'org.team.read'),
		('DISPATCHER', 'ORG', 'org.customer.create'),
		('DISPATCHER', 'ORG', 'org.customer.list'),
		('DISPATCHER', 'ORG', 'org.customer.read'),
		('DISPATCHER', 'ORG', 'org.customer.update'),
		('DISPATCHER', 'ORG', 'org.lead.create'),
		('DISPATCHER', 'ORG', 'org.lead.list'),
		('DISPATCHER', 'ORG', 'org.lead.read'),
		('DISPATCHER', 'ORG', 'org.lead.update'),
		('DISPATCHER', 'ORG', 'org.lead_category.manage'),
		('DISPATCHER', 'ORG', 'org.lead_attachment.manage'),
		('DISPATCHER', 'ORG', 'org.lead_note.manage'),
		('DISPATCHER', 'ORG', 'org.lead_estimate.manage'),
		('DISPATCHER', 'ORG', 'org.job.create'),
		('DISPATCHER', 'ORG', 'org.job.list'),
		('DISPATCHER', 'ORG', 'org.job.read'),
		('DISPATCHER', 'ORG', 'org.job.update'),
		('DISPATCHER', 'ORG', 'org.job_category.manage'),
		('DISPATCHER', 'ORG', 'org.job_assignment.manage'),
		('DISPATCHER', 'ORG', 'org.job_attachment.manage'),
		('DISPATCHER', 'ORG', 'org.job_note.manage'),
		('DISPATCHER', 'ORG', 'org.job_material.manage'),
		('DISPATCHER', 'ORG', 'org.job_estimate.manage'),
		('DISPATCHER', 'ORG', 'org.job_time_entry.manage'),
		('DISPATCHER', 'ORG', 'org.schedule.manage'),
		('DISPATCHER', 'ORG', 'org.material.list'),
		('DISPATCHER', 'ORG', 'org.material.read'),
		('DISPATCHER', 'ORG', 'org.material.update'),
		('TEAM_LEAD', 'ORG', 'org.user.read'),
		('TEAM_LEAD', 'ORG', 'org.user.list'),
		('TEAM_LEAD', 'ORG', 'org.team.manage'),
		('TEAM_LEAD', 'ORG', 'org.team_member.manage'),
		('TEAM_LEAD', 'ORG', 'org.customer.list'),
		('TEAM_LEAD', 'ORG', 'org.customer.read'),
		('TEAM_LEAD', 'ORG', 'org.customer.update'),
		('TEAM_LEAD', 'ORG', 'org.lead.list'),
		('TEAM_LEAD', 'ORG', 'org.lead.read'),
		('TEAM_LEAD', 'ORG', 'org.lead.update'),
		('TEAM_LEAD', 'ORG', 'org.lead_attachment.manage'),
		('TEAM_LEAD', 'ORG', 'org.lead_note.manage'),
		('TEAM_LEAD', 'ORG', 'org.lead_estimate.manage'),
		('TEAM_LEAD', 'ORG', 'org.job.list'),
		('TEAM_LEAD', 'ORG', 'org.job.read'),
		('TEAM_LEAD', 'ORG', 'org.job.update'),
		('TEAM_LEAD', 'ORG', 'org.job_category.manage'),
		('TEAM_LEAD', 'ORG', 'org.job_assignment.manage'),
		('TEAM_LEAD', 'ORG', 'org.job_attachment.manage'),
		('TEAM_LEAD', 'ORG', 'org.job_note.manage'),
		('TEAM_LEAD', 'ORG', 'org.job_material.manage'),
		('TEAM_LEAD', 'ORG', 'org.job_revenue.manage'),
		('TEAM_LEAD', 'ORG', 'org.job_estimate.manage'),
		('TEAM_LEAD', 'ORG', 'org.job_time_entry.manage'),
		('TEAM_LEAD', 'ORG', 'org.schedule.manage'),
		('TEAM_LEAD', 'ORG', 'org.material.list'),
		('TEAM_LEAD', 'ORG', 'org.material.read'),
		('TEAM_LEAD', 'ORG', 'org.material.update'),
		('ORG_SUPPORT_AGENT', 'ORG', 'org.user.read'),
		('ORG_SUPPORT_AGENT', 'ORG', 'org.user.list'),
		('ORG_SUPPORT_AGENT', 'ORG', 'org.team.list'),
		('ORG_SUPPORT_AGENT', 'ORG', 'org.team.read'),
		('ORG_SUPPORT_AGENT', 'ORG', 'org.customer.list'),
		('ORG_SUPPORT_AGENT', 'ORG', 'org.customer.read'),
		('ORG_SUPPORT_AGENT', 'ORG', 'org.lead.list'),
		('ORG_SUPPORT_AGENT', 'ORG', 'org.lead.read'),
		('ORG_SUPPORT_AGENT', 'ORG', 'org.lead_note.create'),
		('ORG_SUPPORT_AGENT', 'ORG', 'org.lead_invoice.list'),
		('ORG_SUPPORT_AGENT', 'ORG', 'org.lead_invoice.read'),
		('ORG_SUPPORT_AGENT', 'ORG', 'org.job.list'),
		('ORG_SUPPORT_AGENT', 'ORG', 'org.job.read'),
		('ORG_SUPPORT_AGENT', 'ORG', 'org.job_assignment.list'),
		('ORG_SUPPORT_AGENT', 'ORG', 'org.job_assignment.read'),
		('ORG_SUPPORT_AGENT', 'ORG', 'org.job_note.create'),
		('ORG_SUPPORT_AGENT', 'ORG', 'org.job_revenue.list'),
		('ORG_SUPPORT_AGENT', 'ORG', 'org.job_revenue.read'),
		('ORG_SUPPORT_AGENT', 'ORG', 'org.job_estimate.list'),
		('ORG_SUPPORT_AGENT', 'ORG', 'org.job_estimate.read'),
		('ORG_SUPPORT_AGENT', 'ORG', 'org.schedule.list'),
		('ORG_SUPPORT_AGENT', 'ORG', 'org.schedule.read'),
		('ORG_SUPPORT_AGENT', 'ORG', 'org.invoice.list'),
		('ORG_SUPPORT_AGENT', 'ORG', 'org.invoice.read'),
		('ORG_SUPPORT_AGENT', 'ORG', 'org.payment.list'),
		('ORG_SUPPORT_AGENT', 'ORG', 'org.payment.read'),
		('ORG_SUPPORT_AGENT', 'ORG', 'org.invitation.list'),
		('ORG_SUPPORT_AGENT', 'ORG', 'org.invitation.read'),
		('MANAGER', 'ORG', 'org.user.read'),
		('MANAGER', 'ORG', 'org.user.list'),
		('MANAGER', 'ORG', 'org.user.update'),
		('MANAGER', 'ORG', 'org.team.manage'),
		('MANAGER', 'ORG', 'org.customer.manage'),
		('MANAGER', 'ORG', 'org.lead.manage'),
		('MANAGER', 'ORG', 'org.lead_category.manage'),
		('MANAGER', 'ORG', 'org.lead_attachment.manage'),
		('MANAGER', 'ORG', 'org.lead_note.manage'),
		('MANAGER', 'ORG', 'org.lead_invoice.manage'),
		('MANAGER', 'ORG', 'org.lead_payment.manage'),
		('MANAGER', 'ORG', 'org.lead_billing.read'),
		('MANAGER', 'ORG', 'org.lead_estimate.manage'),
		('MANAGER', 'ORG', 'org.job.manage'),
		('MANAGER', 'ORG', 'org.job_category.manage'),
		('MANAGER', 'ORG', 'org.job_assignment.manage'),
		('MANAGER', 'ORG', 'org.job_attachment.manage'),
		('MANAGER', 'ORG', 'org.job_material.manage'),
		('MANAGER', 'ORG', 'org.job_note.manage'),
		('MANAGER', 'ORG', 'org.job_revenue.manage'),
		('MANAGER', 'ORG', 'org.job_invoice.manage'),
		('MANAGER', 'ORG', 'org.job_payment.manage'),
		('MANAGER', 'ORG', 'org.job_billing.read'),
		('MANAGER', 'ORG', 'org.job_estimate.manage'),
		('MANAGER', 'ORG', 'org.job_time_entry.manage'),
		('MANAGER', 'ORG', 'org.material.manage'),
		('MANAGER', 'ORG', 'org.schedule.manage'),
		('MANAGER', 'ORG', 'org.invoice.create'),
		('MANAGER', 'ORG', 'org.invoice.list'),
		('MANAGER', 'ORG', 'org.invoice.read'),
		('MANAGER', 'ORG', 'org.invoice.update'),
		('MANAGER', 'ORG', 'org.invoice.export'),
		('MANAGER', 'ORG', 'org.payment.create'),
		('MANAGER', 'ORG', 'org.payment.list'),
		('MANAGER', 'ORG', 'org.payment.read'),
		('MANAGER', 'ORG', 'org.report.read'),
		('MANAGER', 'ORG', 'org.report.list'),
		('MANAGER', 'ORG', 'org.report.export'),
		('MANAGER', 'ORG', 'org.invitation.manage'),
		('ORG_ADMIN', 'ORG', 'org.org.read'),
		('ORG_ADMIN', 'ORG', 'org.org.update'),
		('ORG_ADMIN', 'ORG', 'org.role.manage'),
		('ORG_ADMIN', 'ORG', 'org.permission.manage'),
		('ORG_ADMIN', 'ORG', 'org.billing.manage'),
		('ORG_ADMIN', 'ORG', 'org.user.manage'),
		('ORG_ADMIN', 'ORG', 'org.team.manage'),
		('ORG_ADMIN', 'ORG', 'org.invitation.manage'),
		('ORG_ADMIN', 'ORG', 'org.customer.manage'),
		('ORG_ADMIN', 'ORG', 'org.lead.manage'),
		('ORG_ADMIN', 'ORG', 'org.lead_category.manage'),
		('ORG_ADMIN', 'ORG', 'org.lead_attachment.manage'),
		('ORG_ADMIN', 'ORG', 'org.lead_note.manage'),
		('ORG_ADMIN', 'ORG', 'org.lead_invoice.manage'),
		('ORG_ADMIN', 'ORG', 'org.lead_payment.manage'),
		('ORG_ADMIN', 'ORG', 'org.lead_billing.manage'),
		('ORG_ADMIN', 'ORG', 'org.lead_estimate.manage'),
		('ORG_ADMIN', 'ORG', 'org.job.manage'),
		('ORG_ADMIN', 'ORG', 'org.job_category.manage'),
		('ORG_ADMIN', 'ORG', 'org.job_assignment.manage'),
		('ORG_ADMIN', 'ORG', 'org.job_attachment.manage'),
		('ORG_ADMIN', 'ORG', 'org.job_material.manage'),
		('ORG_ADMIN', 'ORG', 'org.job_note.manage'),
		('ORG_ADMIN', 'ORG', 'org.job_revenue.manage'),
		('ORG_ADMIN', 'ORG', 'org.job_invoice.manage'),
		('ORG_ADMIN', 'ORG', 'org.job_payment.manage'),
		('ORG_ADMIN', 'ORG', 'org.job_billing.manage'),
		('ORG_ADMIN', 'ORG', 'org.job_estimate.manage'),
		('ORG_ADMIN', 'ORG', 'org.job_time_entry.manage'),
		('ORG_ADMIN', 'ORG', 'org.material.manage'),
		('ORG_ADMIN', 'ORG', 'org.schedule.manage'),
		('ORG_ADMIN', 'ORG', 'org.invoice.manage'),
		('ORG_ADMIN', 'ORG', 'org.payment.manage'),
		('ORG_ADMIN', 'ORG', 'org.report.manage'),
		('OWNER', 'ORG', 'org.org.manage'),
		('OWNER', 'ORG', 'org.user.manage'),
		('OWNER', 'ORG', 'org.team.manage'),
		('OWNER', 'ORG', 'org.role.manage'),
		('OWNER', 'ORG', 'org.permission.manage'),
		('OWNER', 'ORG', 'org.invitation.manage'),
		('OWNER', 'ORG', 'org.customer.manage'),
		('OWNER', 'ORG', 'org.lead.manage'),
		('OWNER', 'ORG', 'org.lead_category.manage'),
		('OWNER', 'ORG', 'org.lead_attachment.manage'),
		('OWNER', 'ORG', 'org.lead_note.manage'),
		('OWNER', 'ORG', 'org.lead_invoice.manage'),
		('OWNER', 'ORG', 'org.lead_payment.manage'),
		('OWNER', 'ORG', 'org.lead_billing.manage'),
		('OWNER', 'ORG', 'org.lead_estimate.manage'),
		('OWNER', 'ORG', 'org.lead_report.manage'),
		('OWNER', 'ORG', 'org.job.manage'),
		('OWNER', 'ORG', 'org.job_category.manage'),
		('OWNER', 'ORG', 'org.job_assignment.manage'),
		('OWNER', 'ORG', 'org.job_attachment.manage'),
		('OWNER', 'ORG', 'org.job_material.manage'),
		('OWNER', 'ORG', 'org.job_note.manage'),
		('OWNER', 'ORG', 'org.job_revenue.manage'),
		('OWNER', 'ORG', 'org.job_invoice.manage'),
		('OWNER', 'ORG', 'org.job_payment.manage'),
		('OWNER', 'ORG', 'org.job_billing.manage'),
		('OWNER', 'ORG', 'org.job_estimate.manage'),
		('OWNER', 'ORG', 'org.job_time_entry.manage'),
		('OWNER', 'ORG', 'org.material.manage'),
		('OWNER', 'ORG', 'org.schedule.manage'),
		('OWNER', 'ORG', 'org.invoice.manage'),
		('OWNER', 'ORG', 'org.payment.manage'),
		('OWNER', 'ORG', 'org.billing.manage'),
		('OWNER', 'ORG', 'org.report.manage')
 )
 INSERT INTO public.role_permissions (role_id, permission_id)
 SELECT r.id, p.id
 FROM role_perm_mapping rpm
 JOIN public.roles r ON r.role_name = rpm.role_name::public."RoleEnum" AND r.type = rpm.role_type::public."RoleTypeEnum"
 JOIN public.permissions p ON p.name = rpm.permission_name;