export const API_MESSAGES = {
  GENERAL: {
    UNAUTHORIZED: "Unauthorized access",
    FORBIDDEN: "Forbidden access",
    INTERNAL_SERVER_ERROR: "Internal Server Error",
    BAD_REQUEST: "Bad Request",
    INPUT_VALIDATION_FAILED: "Input Validation Failed",
    TOO_MANY_REQUESTS: "Too Many Requests",
  },
  AUTH: {
    REQUEST_RESET_PASSWORD: "Password reset request sent successfully",
    RESET_PASSWORD: "Password reset successfully",
    REGISTER: "Registered successfully",
    NOT_REGISTER: "Registration failed",
  },
  ORG: {
    ACTIVATED: "Organization activated successfully",
    DEACTIVATED: "Organization deactivated successfully",
    CREATE: "Organization created successfully",
    LIST_MEMBERS: "Organization members fetched successfully",
    LIST_MEMBERS_FOR_SEARCH: "Organization members fetched successfully",
    INVITE_MEMBER: "Member invited successfully",
    NO_ACTIVE_ORGANIZATION: "No active organization found",
    NO_PERMISSION: "No permission to perform this action",
    NOT_MATCHED: "Requested organization and auth organization is not matched",
    GET_BOOKINGS: "Bookings fetched successfully",
    GET_SCHEDULE: "Schedule fetched successfully",
    MEMBER: {
      UPDATE: "Member updated successfully",
      NOT_FOUND: "Member not found",
      NOT_UPDATED: "Failed to update member",
    },
    INVITATION: {
      GET_ALL: "Invitations fetched successfully",
      NOT_FOUND: "Invitation not found",
      NOT_PENDING: "Invitation is not pending",
      NOT_ACTIVE: "Invitation is not active",
      UPDATE: "Invitation updated successfully",
      NOT_UPDATED: "Failed to update invitation",
      ACCEPT: "Invitation accepted successfully",
      REJECT: "Invitation rejected successfully",
      DELETE: "Invitation deleted successfully",
    },
  },
  USER: {
    NOT_FOUND: "User not found",
    NOT_MATCHED: "Requested user and auth user is not matched",
    DELETE: "User deleted successfully",
    BAN: "User banned successfully",
    UNBAN: "User unbanned successfully",
    UPDATE: "User updated successfully",
    UPDATE_PROFILE: "Profile updated successfully",
    GET_STATS: "User Stats fetched successfully",
    GET_ALL: "All Users data is fetched successfully",
    GET_DETAILS: "User details fetched successfully",
    GET_ACTIVITIES: "User activities fetched successfully",
    CREATE_EVENT: "User event created successfully",
    EVENT: {
      CREATED: "User event created successfully",
      ERROR: "User event creation failed",
    },
  },
  ROLE: {
    GET_ALL: "All Roles data is fetched successfully",
    CREATE: "Custom role created successfully",
    UPDATE: "Custom role updated successfully",
    DELETE: "Custom role is deleted successfully",
    EXIST: "Role already exist",
    NOT_FOUND: "Role not found",
  },
  PERMISSION: {
    GET_ALL: "All Permissions data is fetched successfully",
  },
  UPLOAD: {
    GET_SIGNED_URL: "Signed URL fetched successfully",
    GET_DOWNLOAD_URL: "Download URL fetched successfully",
    BLOCK: "File uploading/downloading is blocked",
    CONFIRM_UPLOAD: "File uploaded successfully",
    NOT_CREATE: "File upload failed",
    DELETE: "File deleted successfully",
    NOT_FOUND: "File is not found",
    ASSIGN_ENTITY: "File assigned to entity successfully",
  },
  QSTASH: {
    INVALID_SIGNATURE: "Invalid signature",
  },
  LEAD: {
    EXPORT_ALL: "All leads exported successfully",
    NOT_FOUND: "Lead is not found",
    NOT_CREATED: "Lead is not created",
    CREATED: "Lead is created successfully",
    GET_ALL: "All Leads data is fetched successfully",
    GET_DETAILS: "Lead details fetched successfully",
    GET_HISTORY_DETAILS: "Lead history details fetched successfully",
    GET_ASSIGNMENT_DETAILS: "Lead assignment details fetched successfully",
    GET_ATTACHMENT_DETAILS: "Lead attachment details fetched successfully",
    GET_REVENUE_HISTORY: "Lead revenue history fetched successfully",
    UPDATE: "Lead updated successfully",
    DELETE: "Lead deleted successfully",
    GET_LIST_FOR_SEARCH: "All Leads data for search fetched successfully",
    ASSIGNMENT: {
      CREATE: "Assignment created successfully",
      NOT_CREATE: "Assignment creation failed",
      ALREADY_ASSIGNED: "Member already assigned to this lead",
      UPDATE: "Assignment updated successfully",
      NOT_UPDATE: "Assignment update failed",
      DELETE: "Assignment deleted successfully",
      NOT_DELETE: "Assignment delete failed",
    },
    ATTACHMENT: {
      CREATE: "Attachment created successfully",
      NOT_CREATE: "Attachment creation failed",
      DELETE: "Attachment deleted successfully",
      NOT_FOUND: "Attachment not found",
      NOT_ALLOWED_DELETE: "You are not allowed to delete this attachment",
    },
    HISTORY: {
      CREATE: "History created successfully",
      NOT_CREATE: "History creation failed",
    },
    NOTES: {
      GET_ALL: "All Lead Notes data is fetched successfully",
      CREATE: "Lead note created successfully",
      NOT_CREATE: "Lead note creation failed",
      DELETE: "Lead note deleted successfully",
      NOT_FOUND: "Lead note not found",
      NOT_ALLOWED_DELETE: "You are not allowed to delete this lead note",
      NOT_ALLOWED_UPDATE: "You are not allowed to update this lead note",
      UPDATE: "Lead note updated successfully",
      NOT_UPDATE: "Lead note update failed",
    },
    CUSTOMER: {
      GET_ALL: "All Customer data is fetched successfully",
      NOT_FOUND: "Customer not found",
      NOT_CREATED: "Customer is not created",
    },
    CATEGORY: {
      NOT_FOUND: "Service category not found",
      GET_ALL: "All Service Categories data is fetched successfully",
      CREATE: "Service category created successfully",
      NOT_CREATED: "Service category not created",
    },
  },
};
