export const API_MESSAGES = {
  GENERAL: {
    UNAUTHORIZED: "Unauthorized access",
    FORBIDDEN: "Forbidden access",
    INTERNAL_SERVER_ERROR: "Internal Server Error",
    BAD_REQUEST: "Bad Request",
    INPUT_VALIDATION_FAILED: "Input Validation Failed",
    TOO_MANY_REQUESTS: "Too Many Requests",
  },
  AUTH: {
    REQUEST_RESET_PASSWORD: "Password reset request sent successfully",
    RESET_PASSWORD: "Password reset successfully",
    REGISTER: "Registered successfully",
    NOT_REGISTER: "Registration failed",
  },
  ORG: {
    ACTIVATED: "Organization activated successfully",
    DEACTIVATED: "Organization deactivated successfully",
    CREATE: "Organization created successfully",
    LIST_MEMBERS: "Organization members fetched successfully",
    LIST_MEMBERS_FOR_SEARCH: "Organization members fetched successfully",
    INVITE_MEMBER: "Member invited successfully",
    NO_ACTIVE_ORGANIZATION: "No active organization found",
    NO_PERMISSION: "No permission to perform this action",
    NOT_MATCHED: "Requested organization and auth organization is not matched",
    GET_BOOKINGS: "Bookings fetched successfully",
    GET_SCHEDULE: "Schedule fetched successfully",
    INVITATION: {
      ACCEPT: "Invitation accepted successfully",
      REJECT: "Invitation rejected successfully",
    },
  },
  USER: {
    NOT_FOUND: "User not found",
    NOT_MATCHED: "Requested user and auth user is not matched",
    DELETE: "User deleted successfully",
    BAN: "User banned successfully",
    UNBAN: "User unbanned successfully",
    UPDATE: "User updated successfully",
    UPDATE_PROFILE: "Profile updated successfully",
    GET_STATS: "User Stats fetched successfully",
    GET_ALL: "All Users data is fetched successfully",
    GET_DETAILS: "User details fetched successfully",
    GET_ACTIVITIES: "User activities fetched successfully",
    CREATE_EVENT: "User event created successfully",
    EVENT: {
      CREATED: "User event created successfully",
      ERROR: "User event creation failed",
    },
    PERMISSION: {
      CREATE: "Permission created successfully",
      NOT_CREATE: "Permission creation failed",
      GET_ALL: "All Permissions data is fetched successfully",
      EXIST: "Permission already exists",
    },
    ROLE: {
      GET_ALL: "All Roles data is fetched successfully",
      SET_PERMISSIONS: "Role permissions set successfully",
      NOT_FOUND: "Role not found",
    },
  },
  UPLOAD: {
    GET_SIGNED_URL: "Signed URL fetched successfully",
    GET_DOWNLOAD_URL: "Download URL fetched successfully",
    BLOCK: "File uploading/downloading is blocked",
    CONFIRM_UPLOAD: "File uploaded successfully",
    NOT_CREATE: "File upload failed",
    DELETE: "File deleted successfully",
    NOT_FOUND: "File is not found",
    ASSIGN_ENTITY: "File assigned to entity successfully",
  },
};
