export const API_MESSAGES = {
  GENERAL: {
    UNAUTHORIZED: "Please login to continue.",
    FORBIDDEN: "You don't have permission to perform this action.",
    BAD_REQUEST: "Invalid request. Please check your input and try again.",
    TOO_MANY_REQUESTS: "Too many requests. Please try again later.",
    INPUT_VALIDATION_FAILED: "Please check your input and fix any errors.",
    QSTASH: {
      INVALID_SIGNATURE: "Invalid request signature. Access denied.",
    },
  },
  AUTH: {
    REQUEST_RESET_PASSWORD: "Password reset link has been sent to your email.",
  },
  NOTIFICATION: {
    GET_NOTIFICATIONS: "Notifications loaded successfully.",
    GET_SETTINGS: "Notification settings loaded successfully.",
    UPDATE_SETTINGS: "Notification settings updated successfully.",
    MARK_AS_READ: "Notification marked as read.",
    SUBSCRIBE_PUSH: "Successfully subscribed to push notifications.",
    UNSUBSCRIBE_PUSH: "Successfully unsubscribed from push notifications.",
  },
  ORG: {
    NO_ACTIVE_ORGANIZATION:
      "No active organization found. Please select or create one.",
    ACTIVATED: "Organization activated successfully.",
    CREATE: "Organization created successfully.",
    INVITATION: {
      GET_ALL: "Invitations loaded successfully.",
      ACCEPT: "Invitation accepted successfully.",
      REJECT: "Invitation rejected successfully.",
      NOT_FOUND: "Invitation not found.",
      NOT_PENDING: "This invitation is no longer pending.",
      NOT_ACTIVE: "This invitation is no longer active.",
      NOT_UPDATE: "This invitation is not updated.",
      UPDATE: "Invitation updated successfully.",
      DELETE: "Invitation deleted successfully.",
      INVITE_MEMBER: "Invitation sent successfully.",
    },
    MEMBER: {
      GET_ALL: "Members loaded successfully.",
      NOT_FOUND: "Member not found.",
      NOT_UPDATE: "Member is not updated.",
      UPDATE: "Member updated successfully.",
      GET_ALL_FOR_SEARCH: "Members loaded successfully.",
    },
  },
  USER: {
    GET_ALL: "Users loaded successfully.",
    GET_STATS: "User statistics loaded successfully.",
    GET_DETAILS: "User details loaded successfully.",
    UPDATE: "User updated successfully.",
    NOT_FOUND: "User not found.",
    NOT_MATCHED: "User information doesn't match our records.",
    BAN: "User has been banned successfully.",
    UNBAN: "User has been unbanned successfully.",
    PERMISSION: {
      GET_ALL: "Permissions loaded successfully.",
    },
    ROLE: {
      GET_ALL: "Roles loaded successfully.",
      CREATE: "Role created successfully.",
      EXIST: "Role already exists.",
      DELETE: "Role deleted successfully.",
      UPDATE: "Role updated successfully.",
      NOT_FOUND: "Role not found.",
    },
  },
  UPLOAD: {
    GET_SIGNED_URL: "Upload URL generated successfully.",
    GET_DOWNLOAD_URL: "Download URL generated successfully.",
    CONFIRM_UPLOAD: "Upload confirmed successfully.",
    ASSIGN_ENTITY: "File attached successfully.",
    DELETE: "File deleted successfully.",
    NOT_CREATE: "Failed to create upload. Please try again.",
    NOT_FOUND: "File not found.",
  },
  LEAD: {
    GET_ALL: "Leads loaded successfully.",
    GET_ALL_FOR_SEARCH: "Leads loaded successfully.",
    CREATE: "Lead created successfully.",
    UPDATE: "Lead updated successfully.",
    UPDATE_ADDRESS: "Lead address updated successfully.",
    GET_DETAILS: "Lead details loaded successfully.",
    DELETE: "Lead moved to bin successfully.",
    DELETE_ALL: "All selected leads moved to bin successfully.",
    GET_REVENUE_HISTORY: "Revenue history loaded successfully.",
    NOT_FOUND: "Lead not found.",
    NOT_CREATE: "Failed to create lead. Please try again.",
    CUSTOMER: {
      GET_ALL: "Customers loaded successfully.",
      NOT_CREATE: "Failed to create customer. Please try again.",
      NOT_FOUND: "Customer not found.",
    },
    BIN: {
      RESTORE: "Lead restored successfully.",
      RESTORE_ALL: "All leads restored successfully.",
      DELETE: "Lead deleted permanently.",
      DELETE_ALL: "All leads deleted permanently.",
    },
    CATEGORY: {
      GET_ALL: "Categories loaded successfully.",
      CREATE: "Category created successfully.",
      UPDATE: "Category updated successfully.",
      NOT_CREATE: "Failed to create category. Please try again.",
      NOT_UPDATE: "Failed to update category. Please try again.",
      NOT_FOUND: "Category not found.",
    },
    NOTE: {
      GET_ALL: "Notes loaded successfully.",
      CREATE: "Note created successfully.",
      UPDATE: "Note updated successfully.",
      DELETE: "Note deleted successfully.",
      NOT_CREATE: "Failed to create note. Please try again.",
      NOT_FOUND: "Note not found.",
      NOT_ALLOWED_UPDATE: "You don't have permission to update this note.",
      NOT_UPDATE: "Failed to update note. Please try again.",
      NOT_ALLOWED_DELETE: "You don't have permission to delete this note.",
    },
    ATTACHMENT: {
      GET_DETAILS: "Attachment details loaded successfully.",
      CREATE: "Attachment added successfully.",
      DELETE: "Attachment deleted successfully.",
      NOT_CREATE: "Failed to add attachment. Please try again.",
      NOT_FOUND: "Attachment not found.",
      NOT_ALLOWED_DELETE:
        "You don't have permission to delete this attachment.",
      BIN: {
        GET_ALL: "Deleted attachments loaded successfully.",
        DELETE: "Attachment deleted permanently.",
        RESTORE: "Attachment restored successfully.",
      },
    },
  },
  JOB: {
    GET_ALL: "Jobs loaded successfully.",
    GET_DETAILS: "Job details loaded successfully.",
    GET_ALL_SERVICINGS: "Servicing history loaded successfully.",
    UPDATE_REVENUE: "Revenue updated successfully.",
    NOT_CREATE: "Failed to create job. Please try again.",
    CREATE: "Job created successfully.",
    UPDATE: "Job updated successfully.",
    DELETE: "Job moved to bin successfully.",
    DELETE_ALL: "All selected jobs moved to bin successfully.",
    NOT_UPDATE: "Failed to update job. Please try again.",
    NOT_FOUND: "Job not found.",
    BIN: {
      RESTORE: "Job restored successfully.",
      RESTORE_ALL: "All jobs restored successfully.",
      DELETE: "Job deleted permanently.",
      DELETE_ALL: "All jobs deleted permanently.",
    },
  },
};
