export const colors = {
  background: "#FFFFFF",
  foreground: "#252525",
  card: "#FFFFFF",
  cardForeground: "#252525",
  popover: "#FFFFFF",
  popoverForeground: "#252525",
  primary: "#D48C3B",
  primaryForeground: "#FBF7F0",
  secondary: "#F6F6F7",
  secondaryForeground: "#353536",
  muted: "#F6F7F7",
  mutedForeground: "#8E929B",
  accent: "#D48C3B",
  accentForeground: "#FBF7F0",
  destructive: "#B33A34",
  destructiveForeground: "#FFFFFF",
  border: "#EBECED",
  input: "#EBECED",
  ring: "#C2C6CC",
  sidebar: "#F8F8F8",
};
